// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkY4H_4fA46EMBerjnN_R3oZ-bwA-GOo',
    appId: '1:991550041176:web:660a68c45881cc319dae2d',
    messagingSenderId: '991550041176',
    projectId: 'fir-flutter-codelab-7b0c7',
    authDomain: 'fir-flutter-codelab-7b0c7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7b0c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_lphz66A-FxnRZB9TLVY49VKijdyL0A',
    appId: '1:991550041176:android:9db620fefd07f1159dae2d',
    messagingSenderId: '991550041176',
    projectId: 'fir-flutter-codelab-7b0c7',
    storageBucket: 'fir-flutter-codelab-7b0c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeOHUsmrUBzzh3Xm2Wr3ulUAnhkJSODSc',
    appId: '1:991550041176:ios:be5cfd3e94a10c449dae2d',
    messagingSenderId: '991550041176',
    projectId: 'fir-flutter-codelab-7b0c7',
    storageBucket: 'fir-flutter-codelab-7b0c7.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeOHUsmrUBzzh3Xm2Wr3ulUAnhkJSODSc',
    appId: '1:991550041176:ios:be5cfd3e94a10c449dae2d',
    messagingSenderId: '991550041176',
    projectId: 'fir-flutter-codelab-7b0c7',
    storageBucket: 'fir-flutter-codelab-7b0c7.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
